#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahrytsen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/07 12:02:19 by ahrytsen          #+#    #+#              #
#    Updated: 2017/08/07 13:21:08 by ahrytsen         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME	= ft_cat
SRC		= ft_putchar.c ft_putstr.c ft_putnbr.c ft_cat.c

all:$(NAME)
$(NAME):
	@gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)
clean:
	@/bin/rm -f $(NAME)
fclean: clean
